[workspace]
members = ["src/hello_world", "src/did", "src/pocket-test", "integration-tests"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.85"
repository = "https://github.com/veeso/ic-canister-template"

[workspace.dependencies]
candid = { version = "0.10", features = ["value"] }
ic-cdk = "0.18.2-alpha.1"
ic-cdk-macros = "0.18"
ic-stable-structures = "0.6.8"
serde = "1"

# integration-tests
anyhow = "1"
flate2 = "1"
ic-agent = "0.40"
ic-ledger-types = "0.15.0-alpha.3"
ic-utils = "0.40"
log = "0.4"
pocket-ic = "9"
proc-macro2 = "1"
quote = "1"
reqwest = { version = "0.12" }
syn = "2"
tokio = { version = "1", features = ["full"] }
